server:
  port: 8080
  servlet:
    context-path: /adamstore


spring:
  application:
    name: Spring_AdamStore
  profiles:
    active: dev


# Max Size Upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


app:
  admin:
    email: admin@gmail.com
    password: 123456

  default-avatar-url: https://yourdomain.com/default-avatar.png

  batch-size:
    district: 1000
    ward: 300
    province: 30


auth:
  register:
    verification-code:
      expiration-minutes: 5

  forgot-password:
    verification-code:
      expiration-minutes: 10


cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:3001
    - http://localhost:5174
    - ${EXTRA_ORIGIN:https://default.example.com}


order:
  status:
    processing-to-shipped-days: 1
    shipped-to-delivered-days: 3
    pending-to-cancel-days: 1

location:
  data:
    province-path: classpath:data/provinces.csv
    district-path: classpath:data/districts.csv
    ward-path: classpath:data/wards.csv